export const ACTIONS = {
    MOVIES: {
        GET_MOVIES: "GET_MOVIES",
        GET_MOVIES_SAGA: "GET_MOVIES_SAGA",
        GET_MOVIES_SAGA_SUCSEES: "GET_MOVIES_SAGA_SUCSEES",

    },
    SERIES: {
        GET_SERIES_SAGA: "GET_SERIES_SAGA",
        GET_SERIES_SAGA_SUCSEES: "GET_SERIES_SAGA_SUCSEES"
    },
    ITEM: {
        GET_ITEM_DETAILS: "GET_ITEM_DETAILS",
        GET_ITEM_DETAILS_SUCSEES: "GET_ITEM_DETAILS_SUCSEES",
        REMOVE_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE"

    }

}